name: Airflow CI/CD

on:
  push:
    branches:
      - main
    
    paths:
      -

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install apache-airflow

    - name: Initialize Airflow Database
      run: |
        airflow db init

    - name: Check file path
      run: ls -al

    - name: Check full path
      run: |
        pwd
        ls -a /home/runner/

    - name: Check dag file
      run: |
        cd dags
        ls -a
        

    - name: Run Airflow Tests
      run: |
        ls -lrt
        current_time=$(date -u -d "+1 minutes" "+%Y-%m-%dT%H:%M:%S")
        airflow tasks test fantasy_premier_league_debug current_season_history_bronze_to_silver_test $current_time

    - name: Deploy Airflow DAGs
      run: |
        # Add any deployment steps here, such as copying DAGs to the Airflow DAGs directory